# Generated by Django 2.2.6 on 2019-11-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mancare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlul', models.CharField(max_length=50)),
                ('descriere', models.CharField(max_length=300)),
                ('upload', models.FileField(upload_to='static/img/')),
            ],
        ),
    ]
