# Generated by Django 3.0.1 on 2020-01-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adaugare_Galerie_app', '0004_mancare_data_publicarii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mancare',
            name='titlul',
            field=models.CharField(max_length=50),
        ),
    ]
