# Generated by Django 3.0.1 on 2020-01-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adaugare_Galerie_app', '0005_auto_20200104_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('id_mancare', models.IntegerField()),
            ],
        ),
    ]
