# Generated by Django 3.0.1 on 2020-01-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adaugare_Galerie_app', '0006_favorit'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorit',
            name='salvat',
            field=models.BooleanField(default=False),
        ),
    ]
