# Generated by Django 3.0.3 on 2020-02-16 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adaugare_Galerie_app', '0007_favorit_salvat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mancare',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites_food', to=settings.AUTH_USER_MODEL),
        ),
    ]
